"""Hand curated alias crosswalks built from the Simplified Chinese in-game
localization (names) and the stellarbladeguide.com API (locations/cycles).

Each nano suit entry: (site_id, [aliases], chinese_name, confidence).
The site item with id 61 ("Skin Suit") has no inventory alias.
"""

from __future__ import annotations

# (site_id, aliases, zh, confidence)
NANO_SUITS: list[tuple[int, list[str], str, str]] = [
    (60, ["BS_Green_Suit"], "星球空降服（第7小队）", "high"),
    (61, ["BS_102"], "活肤紧身服", "high"),
    (62, ["BS_08"], "墨黑忍者装", "high"),
    (63, ["BS_08_Var2"], "洁白忍者装", "high"),
    (64, ["BS_OneMillion_01"], "绯红之翼", "high"),
    (65, ["BS_Raven"], "渡鸦装", "high"),
    (117, ["BS_09_2"], "星球空降服（第7小队）第2版", "high"),
    (118, ["BS_09_2_Var2"], "星球空降服（第7小队）第3版", "high"),
    (119, ["BS_05_E", "BS_05"], "星球空降防护服（第7小队）", "high"),
    (141, ["BS_41"], "废土冒险家", "high"),
    (142, ["BS_41_Var2"], "废土探索者", "high"),
    (143, ["BS_15_Var2_E", "BS_15_Var2"], "乌莲", "high"),
    (105, ["BS_38"], "赤血丹心", "high"),
    (106, ["BS_38_Var2"], "翡翠热情", "high"),
    (107, ["BS_14_E", "BS_14"], "芍药独韵", "high"),
    (893, ["BS_99"], "星球空降服（队长）", "high"),
    (895, ["BS_01_Var2"], "占星服", "high"),
    (908, ["BS_Christmas_01"], "圣诞裙装", "high"),
    (936, ["BS_02"], "星球空降服（第2小队）", "high"),
    (937, ["BS_02_Var2"], "星球空降服（第2小队）第2版", "high"),
    (938, ["BS_48"], "奥卡探索者", "high"),
    (939, ["BS_48_Var2"], "奥卡探路者", "high"),
    (940, ["BS_01"], "镂空服", "high"),
    (941, ["BS_01_Var3"], "镂空裙装", "high"),
    (942, ["BS_32"], "“四秒钟”破洞牛仔布套装", "high"),
    (943, ["BS_56"], "盛夏爱丽丝", "high"),
    (944, ["BS_57"], "盛夏小红帽", "high"),
    (945, ["BS_15"], "国色牡丹", "high"),
    (946, ["BS_03"], "赛博裙装", "high"),
    (947, ["BS_03_Var2"], "赛博服装", "high"),
    (948, ["BS_17"], "赛博兔女郎", "high"),
    (954, ["BS_Yellow_Suit"], "星球空降服原型", "high"),
    (955, ["BS_Yellow_Suit_Var2"], "星球空降服原型第2版", "high"),
    (1004, ["BS_Leather_Jean"], "休闲车手服", "high"),
    (1005, ["BS_Leather_Jean_Var2"], "“四秒钟”车手服", "high"),
    (1006, ["BS_11"], "黑礼服", "high"),
    (1007, ["BS_10"], "白礼服", "high"),
    (1008, ["BS_23"], "废料机械师", "high"),
    (1009, ["BS_23_Var2"], "废品工程师", "high"),
    (1010, ["BS_EVE_04"], "牛仔布休闲装", "high"),
    (1011, ["BS_EVE_04_Var2"], "“四秒钟”牛仔布套装", "high"),
    (1019, ["BS_Bear"], "毛绒熊熊", "high"),
    (1020, ["BS_Bear_Var2"], "粉红小熊", "high"),
    (1021, ["BS_30"], "空中王牌", "high"),
    (1022, ["BS_30_Var2"], "天骄王牌", "high"),
    (1031, ["BS_19"], "黑珍珠", "high"),
    (1032, ["BS_19_Var2"], "赤色珍珠", "high"),
    (1033, ["BS_26"], "“四秒钟”休闲装", "high"),
    (1034, ["BS_53"], "神经元链接紧身服", "high"),
    (1035, ["BS_33"], "“四秒钟”黑色牛仔布套装", "high"),
    (1036, ["BS_55"], "烽火裙装", "high"),
    (716, ["BS_45"], "狂飙车手", "high"),
    (717, ["BS_45_Var2"], "极速快感", "high"),
    (718, ["BS_53_Var2"], "知觉活肤紧身服", "high"),
    (731, ["BS_Nier_01"], "寄叶二号B型制服", "medium"),
    (732, ["BS_Nier_02"], "寄叶制服1", "medium"),
    (733, ["BS_Nier_03"], "寄叶非官方仪式礼服", "medium"),
    (734, ["BS_Nier_04"], "寄叶A型二号制服", "medium"),
    (786, ["BS_24_E", "BS_24"], "通勤装", "high"),
    (787, ["BS_24_Var2"], "空乘风", "high"),
    (795, ["BS_37_Var2"], "玫瑰人生", "high"),
    (796, ["BS_33_Var2"], "“四秒钟”条纹牛仔布套装", "high"),
    (798, ["BS_Nikke_05"], "清凉装", "low"),
    (799, ["BS_Nikke_01"], "优雅礼服", "low"),
    (800, ["BS_Nikke_02"], "极乐净土战斗服", "low"),
    (801, ["BS_Nikke_04"], "失落之链", "low"),
    (802, ["BS_Nikke_03"], "永不回头", "low"),
    (880, ["BS_16"], "假日兔", "high"),
    (881, ["BS_16_Var2"], "假日兔女郎", "high"),
    (882, ["BS_50"], "神经元链接套装原型", "high"),
    (884, ["BS_44"], "赛博魔法师", "high"),
    (885, ["BS_44_Var2"], "赛博诡术士", "high"),
    (886, ["BS_21"], "莹白珍珠", "high"),
    (745, ["BS_34"], "黄色运动服", "high"),
    (746, ["BS_34_Var2"], "活力运动服", "high"),
    (747, ["BS_43_Var2"], "极致兔女郎", "high"),
    (463, ["BS_04"], "休闲针织裙装", "high"),
    (464, ["BS_04_Var2"], "舒适针织裙装", "high"),
    (465, ["BS_21_Var2"], "水珍珠", "high"),
    (565, ["BS_13"], "休闲吉祥物装", "high"),
    (566, ["BS_13_Var2"], "舒适吉祥物装", "high"),
    (567, ["BS_SilverKunoichi_Var2"], "暗影忍者装", "high"),
    (609, ["BS_SilverKunoichi"], "亮银忍者装", "high"),
    (530, ["BS_31"], "休闲活力装", "high"),
    (531, ["BS_31_Var2"], "舒适活力装", "high"),
    (532, ["BS_Blue_Suit_E", "BS_Blue_Suit"], "星球空降服（第5小队）", "high"),
    (534, ["BS_18"], "海洋之丝", "high"),
    (344, ["BS_20"], "碧蓝季风", "high"),
    (345, ["BS_20_Var2"], "纯白季风", "high"),
    (346, ["BS_26_Var2"], "“四秒钟”基本造型", "high"),
    (355, ["BS_Black_Leather_bikini"], "墨色波浪", "high"),
    (356, ["BS_Black_Leather_bikini_Var2"], "怒涛", "high"),
    (357, ["BS_54"], "烽火神盾", "high"),
    (384, ["BS_Sailor_Jean"], "休闲水手服", "high"),
    (385, ["BS_Sailor_Jean_Var2"], "舒适水手服", "high"),
    (386, ["BS_50_Var2"], "知觉套装原型", "high"),
    (400, ["BS_40"], "赛博绑带装", "high"),
    (401, ["BS_40_Var2"], "自动绑带装", "high"),
    (402, ["BS_40_Var3_E", "BS_40_Var3"], "神经元回路绑带装", "high"),
    (403, ["BS_22"], "海的女仆", "high"),
    (404, ["BS_22_Var2_E", "BS_22_Var2"], "海潮女仆", "high"),
    (405, ["BS_58"], "“波浪”潜水比基尼", "high"),
    (406, ["BS_60"], "“波浪”斜款连体比基尼", "high"),
    (4, ["BS_Yellow_Suit_Jacket"], "星球空降服（第3小队）", "high"),
    (5, ["BS_Yellow_Suit_Jacket_Var2"], "星球空降服（第3小队）第2版", "high"),
    (6, ["BS_05_Var2_E", "BS_05_Var2"], "星球空降防护服（第7小队）第2版", "high"),
    (219, ["BS_Default"], "星球空降服（第6小队）", "high"),
    (220, ["BS_Default_Var2"], "星球空降服（第6小队）第2版", "high"),
    (221, ["BS_Default_Var3"], "星球空降服（第6小队）第3版", "high"),
    (241, ["BS_White_Jean"], "朋克炸街服", "high"),
    (242, ["BS_White_Jean_Var2"], "朋克风", "high"),
    (243, ["BS_14_Var2_E", "BS_14_Var2"], "绣球花", "high"),
    (261, ["BS_42"], "动力十足", "high"),
    (262, ["BS_42_Var2"], "共鸣", "high"),
    (263, ["BS_55_Var2"], "烽火装", "high"),
    (607, ["BS_07"], "奥卡工程师", "high"),
    (608, ["BS_07_Var2"], "奥卡技术员", "high"),
    (650, ["BS_37"], "黑玫瑰", "high"),
    (651, ["BS_37_Var3"], "天使玫瑰", "high"),
    (652, ["BS_43"], "终极兔女郎", "high"),
    (692, ["BS_47"], "目光焦点", "high"),
    (693, ["BS_47_Var2"], "丽影", "high"),
    (56, ["BS_52"], "神经元链接套装", "high"),
    (57, ["BS_44_Var3_E", "BS_44_Var3"], "赛博幻术师", "high"),
    (58, ["BS_RoyalGuard_01"], "神圣护卫套装", "high"),
    (59, ["BS_Nikke_06"], "流浪剑客", "low"),
]

# (site_id, aliases, zh, category, confidence)
APPEARANCE: list[tuple[int, list[str], str, str, str]] = [
    (67, ["Hair_000"], "星球空降马尾", "hair", "high"),
    (913, ["Hair_Christmas_01"], "圣诞女孩", "hair", "high"),
    (1037, ["Hair_006"], "女儿的回忆", "hair", "high"),
    (1038, ["Hair_001"], "卡西姆的抉择", "hair", "high"),
    (1039, ["Hair_002"], "最可爱的发型", "hair", "high"),
    (1040, ["Hair_003"], "希雍公主", "hair", "high"),
    (1041, ["Hair_004"], "桃香", "hair", "high"),
    (1042, ["Hair_005"], "哥特时代", "hair", "high"),
    (1043, ["Hair_007"], "初恋", "hair", "high"),
    (1044, ["Hair_008"], "武士刀", "hair", "high"),
    (1045, ["Hair_009"], "情人节", "hair", "high"),
    (1046, ["Hair_010"], "卡西姆的招牌发型", "hair", "high"),
    (1047, ["Hair_011"], "假日", "hair", "high"),
    (1048, ["Hair_012"], "创新之作", "hair", "high"),
    (736, ["Hair_Nier_001"], "寄叶二号B型发型", "hair", "medium"),
    (737, ["Hair_Nier_002"], "白狐面具发型", "hair", "medium"),
    (738, ["Hair_Nier_003"], "寄叶A型二号发型", "hair", "medium"),
    (803, ["Hair_Nikke_01"], "高贵优雅", "hair", "low"),
    (804, ["Hair_Nikke_02"], "标准长发", "hair", "low"),
    (805, ["Hair_Nikke_03"], "元气刘海", "hair", "low"),
    (806, ["Hair_Nikke_04"], "初恋", "hair", "low"),
    (807, ["Hair_Nikke_05"], "活力双马尾", "hair", "low"),
    (1057, ["Hair_Nikke_06"], "月光美人", "hair", "low"),
    (897, ["FaceAccessory_012"], "半框眼镜", "glasses", "high"),
    (912, ["FaceAccessory_Christmas_01"], "冰晶眼镜", "glasses", "high"),
    (735, ["FaceAccessory_Nier_001"], "战斗护目镜", "glasses", "medium"),
    (862, ["FaceAccessory_001"], "椭圆角质架眼镜", "glasses", "high"),
    (863, ["FaceAccessory_005"], "金属框架眼镜", "glasses", "high"),
    (864, ["FaceAccessory_006"], "猫眼", "glasses", "high"),
    (865, ["FaceAccessory_004"], "棕色角质架眼镜", "glasses", "high"),
    (866, ["FaceAccessory_007"], "实验室护目镜", "glasses", "high"),
    (867, ["FaceAccessory_010"], "多边形方框眼镜", "glasses", "high"),
    (868, ["FaceAccessory_011"], "方框眼镜", "glasses", "high"),
    (869, ["FaceAccessory_026"], "环绕式太阳镜", "glasses", "high"),
    (870, ["FaceAccessory_003"], "经典圆框眼镜", "glasses", "high"),
    (871, ["FaceAccessory_008"], "超窄太阳镜", "glasses", "high"),
    (872, ["FaceAccessory_009"], "橙色飞行员太阳镜", "glasses", "high"),
    (873, ["FaceAccessory_013"], "超大号太阳镜", "glasses", "high"),
    (874, ["FaceAccessory_028"], "眼罩", "glasses", "high"),
    (875, ["FaceAccessory_027"], "漩涡眼镜", "glasses", "high"),
    (407, ["FaceAccessory_029"], "偏光太阳镜", "glasses", "high"),
    (583, ["FaceAccessory_002"], "大圆框眼镜", "glasses", "high"),
    (584, ["FaceAccessory_002_Var2"], "超大圆框眼镜", "glasses", "high"),
    (66, ["Earring_018"], "承传标记", "earrings", "high"),
    (101, ["Earring_001"], "绯红泪珠", "earrings", "high"),
    (102, ["Earring_001_Var2"], "高贵泪珠", "earrings", "high"),
    (103, ["Earring_012"], "黄金之心", "earrings", "high"),
    (113, ["Earring_008"], "记忆耳坠", "earrings", "high"),
    (114, ["Earring_008_Var2"], "闪亮记忆", "earrings", "high"),
    (115, ["Earring_014"], "水晶之泪", "earrings", "high"),
    (896, ["Earring_011"], "四倍矩形", "earrings", "high"),
    (910, ["Earring_Christmas_02"], "雪橇耳夹", "earrings", "high"),
    (911, ["Earring_Christmas_01"], "花环耳饰", "earrings", "high"),
    (978, ["Earring_004"], "聚变之光", "earrings", "high"),
    (979, ["Earring_006"], "绿松石环", "earrings", "high"),
    (980, ["Earring_007"], "太阳之泪", "earrings", "high"),
    (981, ["Earring_017"], "黄金枝", "earrings", "high"),
    (982, ["Earring_009"], "辐射钟摆", "earrings", "high"),
    (983, ["Earring_010"], "黑色矩形", "earrings", "high"),
    (984, ["Earring_015"], "红宝石之泪", "earrings", "high"),
    (985, ["Earring_016"], "摇摆兔兔", "earrings", "high"),
    (986, ["Earring_005"], "护耳", "earrings", "high"),
    (453, ["Earring_002"], "点点蓝晶", "earrings", "high"),
    (454, ["Earring_002_Var2"], "光点", "earrings", "high"),
    (455, ["Earring_013"], "美玉良珀", "earrings", "high"),
    (634, ["Earring_003"], "银齿", "earrings", "high"),
    (635, ["Earring_003_Var2"], "金齿", "earrings", "high"),
    (68, ["DroneSeal_001"], "战术包", "drone_seals", "high"),
    (133, ["DroneSeal_003"], "装甲包", "drone_seals", "high"),
    (134, ["DroneSeal_002_Var2"], "铁甲套装", "drone_seals", "high"),
    (894, ["DroneSeal_005"], "毛绒熊熊套装", "drone_seals", "high"),
    (898, ["DroneSeal_002"], "占星师套装", "drone_seals", "high"),
    (907, ["DroneSeal_Christmas_01"], "驯鹿鲁道夫套装", "drone_seals", "high"),
    (739, ["DroneSeal_Nier_001"], "波德042套装", "drone_seals", "medium"),
    (619, ["DroneSeal_004"], "兔宝宝套装", "drone_seals", "high"),
    (620, ["DroneSeal_004_Var2"], "迷你兔套装", "drone_seals", "high"),
    (70, ["AdamCostume_001"], "下水道老鼠", "adam_costumes", "high"),
    (899, ["AdamCostume_002"], "占星师服装", "adam_costumes", "high"),
    (909, ["AdamCostume_Christmas_01"], "我不是圣诞老人", "adam_costumes", "high"),
    (741, ["AdamCostume_Nier_001"], "埃米尔头部", "adam_costumes", "medium"),
    (792, ["AdamCostume_003"], "拾荒人", "adam_costumes", "high"),
    (793, ["AdamCostume_003_Var2"], "废品回收人", "adam_costumes", "high"),
    (478, ["AdamCostume_004"], "变色龙", "adam_costumes", "high"),
    (479, ["AdamCostume_004_Var2"], "夜鹰", "adam_costumes", "high"),
    (69, ["LilyCostume_001"], "阿尔忒弥斯", "lily_costumes", "high"),
    (900, ["LilyCostume_002"], "占星师外套", "lily_costumes", "high"),
    (714, ["LilyCostume_003"], "忧郁之雨", "lily_costumes", "high"),
    (715, ["LilyCostume_003_Var2"], "雨天", "lily_costumes", "high"),
    (740, ["LilyCostume_Nier_001"], "寄叶9号S型制服", "lily_costumes", "medium"),
    (440, ["LilyCostume_004"], "休假日", "lily_costumes", "high"),
    (441, ["LilyCostume_004_Var2"], "休息日", "lily_costumes", "high"),
]

# Fish aliases -> Simplified Chinese names.
FISH_ZH: dict[str, str] = {
    "Fish_Arowana": "龙鱼",
    "Fish_Betta": "斗鱼",
    "Fish_ButterflyFish": "蝴蝶鱼",
    "Fish_CannedFish": "鱼罐头",
    "Fish_ChannelCatfish": "斑点叉尾鮰",
    "Fish_Dunkleosteus": "盾皮鱼",
    "Fish_FancyCarp": "锦鲤",
    "Fish_FishCake": "鱼饼",
    "Fish_FlyingFish": "飞鱼",
    "Fish_FootBallfish": "足球鱼",
    "Fish_Goby": "虾虎鱼",
    "Fish_Goldfish": "金鱼",
    "Fish_GoldFish": "金鱼",
    "Fish_GreatWhiteShark": "大白鲨",
    "Fish_Halibut": "大比目鱼",
    "Fish_Lobster": "龙虾",
    "Fish_MahiMahi": "鲯鳅",
    "Fish_Mahimahi": "鲯鳅",
    "Fish_MolaMola": "翻车鱼",
    "Fish_NuclearWaste": "核废料",
    "Fish_Pirarucu": "巨骨舌鱼",
    "Fish_PorcupineFish": "刺豚",
    "Fish_SailFish": "旗鱼",
    "Fish_Salmon": "鲑鱼",
    "Fish_SeaBass": "海鲈鱼",
    "Fish_SeaBream": "真鲷",
    "Fish_Tire": "轮胎",
    "Fish_Triggerfish": "扳机鱼",
    "Fish_Tuna": "金枪鱼",
    "Fish_WhaleShark": "鲸鲨",
    "Fish_mackerel": "鲭鱼",
    "Fish_Nikke_Glasses": "妮姬·眼镜",
    "Fish_Nikke_Laplace": "妮姬·拉普拉斯",
    "Fish_Nikke_Poli": "妮姬·波莉",
    "Fish_Nikke_Rapunzel": "妮姬·长发公主",
    "Fish_Nikke_SnowWhite": "妮姬·白雪",
    "Fish_Nikke_Tape": "妮姬·磁带",
}

# Zone code -> Chinese label (records / camps).
ZONE_ZH: dict[str, str] = {
    "Day1": "第一天",
    "Xion": "希雍",
    "WLA": "废土A",
    "WLB": "废土B",
    "DED10": "大沙漠1",
    "DED20": "大沙漠2",
    "DED30": "大沙漠3",
    "DED40": "大沙漠4",
    "ME01": "矩阵11-1",
    "ME03": "矩阵11-3",
    "ME04": "矩阵11-4",
    "ME05": "矩阵11-5",
    "ME06": "矩阵11-6",
    "ME": "矩阵11",
    "SE": "尖塔4(推测)",
    "DED": "大沙漠",
    "ME_01": "矩阵11-1",
    "ME_03": "矩阵11-3",
    "ME_04": "矩阵11-4",
    "ME_05": "矩阵11-5",
    "ME_06": "矩阵11-6",
    "ATL": "阿尔忒斯勒瓦尔",
    "AYL": "深渊勒瓦尔",
    "SE01": "尖塔1",
    "SE02": "尖塔2",
    "SE04": "尖塔4",
    "SE05": "尖塔5",
    "SE06": "尖塔6",
    "SE07": "尖塔7",
    "SE08": "尖塔8",
    "SE09": "尖塔9",
    "ETC": "其他",
    "Christmas": "圣诞",
    "Nest": "巢穴",
}

DLC_LABEL = "DLC"

# Guide site levels use these names; kept here so the builder can label zones.
SITE_BASE_URL = "https://stellarbladeguide.com"
